### ISSUE TITLE
Example app https://crowd-source.herokuapp.com/ is dead

### ISSUE THREAD

**Issue by asmaier** [as-ideas/crowdsource#41]
The Readme points to an example installation at https://crowd-source.herokuapp.com/ . Unfortunately the example app doesn't work anymore.

**Comment by wThomas84** [comment]
Hi Andreas, 
thanks for the advice. This is caused by changes Heroku made regarding its infrastructure. Will investigate soon.

**Comment by wThomas84** [comment]
If you cannot wait to see the current version in action just run locally by:

* Clone this repo
* Start Local MongoDb by executing in root of your clone:
 `mvn com.github.joelittlejohn.embedmongo:embedmongo-maven-plugin:0.1.12:start -Dembedmongo.wait -Dmongodb.test.port=27017`
* Start application from directory `crowdsource-example`:
 `mvn spring-boot:run`

**Comment by wThomas84** [comment]
Fixed.
